[package]
name = "zentime-rs"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "zentime"
path = "src/main.rs"

[dependencies]
figment = { version = "0.10", features = ["toml"] }
rodio = "0.12"
anyhow = "1"
notify-rust = "4"
serde = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive"] }
crossterm = "0.25.0"
tui = "0.19.0"
shellexpand = "2.1.0"
